### ISSUE TITLE
Proposed biggus.save enhancement

### ISSUE THREAD

**Issue by cpelley** [SciTools/biggus#172]
I propose to add a keyword argument to [save](https://github.com/SciTools/biggus/blob/f150a2074c2f363c5e6c67821c1322e07e089858/biggus/__init__.py) (operation).  The context of this, is to provide the capability to perform dtype conversions on save.  In particular, when saving to NetCDF classic or true CF compliant NetCDF, an unsigned dtype conversion to a signed alternative is necessary.  Having such an operation is not restricted to this example, however, this is my motivation.

```Python
def biggus.save(sources, targets, masked=False, operation=None):
    """
    Save the numeric results of each source into its corresponding target.

    Parameters
    ---------------
    ...
    operation : callable
        Callable to apply to the source before saving.
    ...

```

Happy to make the enhancement myself if this is deemed useful.

**Comment by rhattersley** [comment]
Hi @cpelley - thanks for explaining the problem, its background, and proposing a solution all in one! :+1: for allowing a change of dtype, but changing dtype is orthogonal to saving. Rather than modify `save` you should be able to use `_Elementwise`. Something like:
```python
def astype(a, dtype):
    def _astype(chunk):
        return chunk.astype(dtype)
    return _Elementwise(a, None, _astype, _astype)
```
Now save is kept simple and you change dtype at any point in a processing chain.

**Comment by cpelley** [comment]
Gosh thanks @rhattersley, I didn't realise.  Love it!
